routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::group(['middleware' => ['auth']], function() {

    Route::get('/', 'DashboardController@index')->name('dashboard');

    Route::group(['middleware' => ['isAdmin']], function() {
        Route::resource('event', 'EventController', ['except' => ['destroy']]);
        Route::get('event/{event}/delete', 'EventController@destroy')->name('event.delete');

        Route::name('workshop.')->prefix('workshop')->group(function() {
            Route::get('create/{event}', 'WorkshopController@create')->name('create');
            Route::get('{workshop}/delete', 'WorkshopController@destroy')->name('delete');
            Route::get('schedule/{filterDate?}', 'WorkshopController@schedule')->name('schedule');
        });
        Route::resource('workshop', 'WorkshopController', ['except' => ['create', 'destroy']]);

        Route::name('session.')->prefix('session')->group(function() {
            Route::get('create/{workshop}', 'WorkshopSessionController@create')->name('create');
            Route::get('{workshop}/delete', 'WorkshopSessionController@destroy')->name('delete');
        });
        Route::resource('session', 'WorkshopSessionController', ['except' => ['create', 'destroy']]);

        Route::name('participant.')->prefix('participant')->group(function() {
            Route::get('{participant}/delete', 'ParticipantController@destroy')->name('delete');
            Route::get('create/{workshop}', 'ParticipantController@createInWorkshop')->name('createInWorkshop');
            Route::post('store/{workshop}', 'ParticipantController@storeInWorkshop')->name('storeInWorkshop');
            Route::get('show/{workshop}', 'ParticipantController@show')->name('showAvailable');
        });
        Route::resource('participant', 'ParticipantController', ['except' => ['destroy']]);
    });

    Route::group(['middleware' => ['isSuper']], function() {
        Route::prefix('user-management')->namespace('UserManagement')->group(function() {
            Route::resource('user', 'UserController', ['except' => ['destroy']]);
            Route::get('user/{user}/delete', 'UserController@destroy')->name('user.delete');
        });
    });
    
    Route::name('attendance.')->prefix('attendance')->group(function() {
        Route::get('/', 'ParticipantAttendanceController@index')->name('index');
        Route::get('{event}/workshop', 'ParticipantAttendanceController@workshop')->name('workshop');
        Route::get('{workshopSession}/scan', 'ParticipantAttendanceController@scan')->name('scan');
        Route::get('{workshopSession}/report', 'ParticipantAttendanceController@report')->name('report');
        Route::get('{event}/overallEventReport', 'EventController@overallReport')->name('overallEventReport');
        Route::get('{event}/exportOverallEventReport', 'EventController@exportOverallReport')->name('exportOverallEventReport');
        Route::get('{workshop}/overallReport', 'ParticipantAttendanceController@overallReport')->name('overallReport');
        Route::get('{workshop}/exportOverallReport', 'ParticipantAttendanceController@exportOverallReport')->name('exportOverallReport');
        Route::post('register', 'ParticipantAttendanceController@register')->name('register');
        Route::get('{attendance}/delete', 'ParticipantAttendanceController@destroy')->name('delete');
        Route::get('{event}/redirect', 'ParticipantAttendanceController@redirectToWorkshop')->name('redirect');
    });

    Route::prefix('api/v0')->namespace('Apis\v0')->group(function() {
        Route::get('/scan', 'ParticipantAttendanceController@scanBarcode')->name('scan');
        Route::get('/updateTime/{workshopId}/{participantId}', 'ParticipantAttendanceController@updateAttendanceParticipantTime')->name('updateTime');
    });

});

app/Participant.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Participant extends Model
{
    protected $table = 'peserta';

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'kode_peserta',
        'no_ktp',
        'nama',
        'no_kta',
        'institusi',
        'email',
        'no_telp',
        'jk',
        'barcode',
        'created_by',
        'updated_by'
    ];
}

app/Http/Controllers/ParticipantController.php
<?php

namespace App\Http\Controllers;

use Auth;
use App\Participant;
use App\ParticipantAttendance;
use App\WorkshopParticipant;
use App\Http\Requests\ParticipantRequest;
use App\Http\Utilities\Utilities;
use Illuminate\Http\Request;

class ParticipantController extends Controller
{
    use Utilities;

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $participants = Participant::orderBy('nama')->get();

        return view('participant.index', compact('participants'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $participant = new Participant;

        return view('participant.create', compact('participant'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(ParticipantRequest $request)
    {
        $data = $request->all();
        // $data['created_by'] = Auth::user()->name;
        $participant = Participant::create($data);

        return redirect()->route('participant.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($workshopId)
    {
        $existParticipants = WorkshopParticipant::where('jadwal_materi_id', $workshopId)
            ->pluck('peserta_id')
            ->all();
        $participants = Participant::whereNotIn('id', $existParticipants)
            ->orderBy('nama')
            ->get();

        return view('participant.workshop.list', compact('workshopId', 'participants'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $participant = Participant::findOrFail($id);

        return view('participant.edit', compact('participant'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(ParticipantRequest $request, $id)
    {
        $participant = Participant::findOrFail($id);
        $data = $request->all();
        // $data['updated_by'] = Auth::user()->name;
        $participant->update($data);

        return redirect()->route('participant.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $participant = Participant::findOrFail($id);
        $participant->delete();

        return redirect()->route('participant.index');
    }

    /**
     * Show the form for creating a new resource in workshop page.
     *
     * @param  int  $workshopId
     * @return \Illuminate\Http\Response
     */
    public function createInWorkshop($workshopId)
    {
        $participant = new Participant;

        return view('participant.workshop.create', compact('workshopId', 'participant'));
    }

    /**
     * Create new participant in event and insert it into absen_peserta table.
     *
     * @param  int  $workshopId
     * @return \Illuminate\Http\Response
     */
    public function storeInWorkshop(ParticipantRequest $request, $workshopId)
    {
        $data = $request->all();
        $participant = new Participant;
        $participant->fill($data);

        if ($participant->save()) {
            $participantId = $participant->id;
            $workshopParticipant = new WorkshopParticipant;
            $workshopParticipant->jadwal_materi_id = $workshopId;
            $workshopParticipant->peserta_id = $participantId;

            if ($workshopParticipant->save()) {
                $this->generateAttendance($workshopId, null, $workshopParticipant->peserta_id);
            }

            return redirect()->route('workshop.show', ['id' => $workshopId]);
        }

        return redirect()->route('participant.index');
    }
}

resources/views/participant/_participant.blade.php
<div class="card">
    <div class="card-body">
        <div class="form-group">
            {!! Form::hidden('id', null) !!}
            {!! Form::label('kode_peserta', 'Participant Code:') !!}
            {!! Form::text('kode_peserta', null, ['class' => 'form-control']) !!}
        </div>
        <div class="form-group">
            {!! Form::label('no_ktp', 'Identity Number:') !!}
            {!! Form::text('no_ktp', null, ['class' => 'form-control']) !!}
        </div>
        <div class="form-group">
            {!! Form::label('nama', 'Name:') !!}
            {!! Form::text('nama', null, ['class' => 'form-control']) !!}
        </div>
        <div class="form-group">
            {!! Form::label('no_kta', 'KTA Number:') !!}
            {!! Form::text('no_kta', null, ['class' => 'form-control']) !!}
        </div>
        <div class="form-group">
            {!! Form::label('institusi', 'Institute:') !!}
            {!! Form::text('institusi', null, ['class' => 'form-control']) !!}
        </div>
        <div class="form-group">
            {!! Form::label('email', 'Email:') !!}
            {!! Form::email('email', null, ['class' => 'form-control']) !!}
        </div>
        <div class="form-group">
            {!! Form::label('no_telp', 'Phone Number:') !!}
            {!! Form::text('no_telp', null, ['class' => 'form-control']) !!}
        </div>
        <div class="form-group">
            {!! Form::label('jk', 'Sex:') !!}
            {!! Form::select('jk', ['L' => 'Male', 'P' => 'Female'], 'L', ['class' => 'form-control']) !!}
        </div>
        <div class="form-group">
            {!! Form::label('barcode', 'Barcode:') !!}
            {!! Form::text('barcode', null, ['class' => 'form-control']) !!}
        </div>
        <div class="form-group">
            {!! Form::submit($submitLabel, ['class' => 'btn btn-primary form-control']) !!}
            <a onclick="window.history.back()" class="btn btn-danger form-control text-white">Cancel</a>
        </div>
    </div>
</div>

resources/views/participant/_table.blade.php
<a href="{{ route('participant.createInWorkshop', ['workshopId' => $workshop->id ]) }}" class="btn btn-success btn-sm mb-2">
    <i class="fa fa-plus-circle"></i> Create New Participant
</a>
<a href="{{ route('participant.showAvailable', ['workshopId' => $workshop->id ]) }}" class="btn btn-warning btn-sm mb-2 text-white">
    <i class="fa fa-user-plus"></i> Add From Existing
</a>
<table id="participantDtab" class="table table-xs table-striped table-bordered" style="width=100%">
    <thead>
        <tr>
            <th></th>
            <th>Participant Number</th>
            <th>Name</th>
            <th>Institution</th>
            <th>Attendance Duration (Minutes)</th>
            <th>Attendance Percentation (%)</th>
            <th>Certificate</th>
        </tr>
    </thead>
    <tbody>
        @forelse ($participants as $participant)
            <tr>
                <td class="align-middle">
                    <span>
                        <a onclick="return confirm('Are you sure to remove participant?')" href="{{ route('attendance.delete', ['id' => $participant->id]) }}" class="btn btn-outline-danger btn-sm" title="Remove Participant">
                            <i class="fa fa-user-times"></i>
                        </a>
                    </span>
                </td>
                <td>{{ $participant->kode_peserta }}</td>
                <td>{{ $participant->nama }}</td>
                <td>{{ $participant->institusi }}</td>
                <td>{{ $participant->waktu_kehadiran }}</td>
                <td>{{ $participant->persentase_kehadiran }}</td>
                <td class="text-center">
                    {!! Form::checkbox('certificate_'. $participant->peserta_id, '1', ($participant->cetak_sertifikat) ? true : false, ['disabled']); !!}
                </td>
            </tr>
        @empty
            <tr>
                <td colspan="7" class="text-center text-muted">No data</td>
                <td style="display: none;"></td>
                <td style="display: none;"></td>
                <td style="display: none;"></td>
                <td style="display: none;"></td>
                <td style="display: none;"></td>
                <td style="display: none;"></td>
            </tr>
        @endforelse
    </tbody>
</table>

resources/views/participant/create.blade.php
@extends('layouts.app-base')

@section('content')

<div class="panel panel-primary">
    <div class="panel-heading">Create Participant</div>
    <div class="panel-body">

    {!! Form::model($participant, ['route' => 'participant.store']) !!}

        @include('participant._participant', ['submitLabel' => 'Save'])

    {!! Form::close() !!}

    @include('errors.validation-error')

    </div>
</div>

@stop

resources/views/participant/edit.blade.php
@extends('layouts.app-base')

@section('content')

<div class="panel panel-primary">
    <div class="panel-heading">Edit Participant</div>
    <div class="panel-body">

    {!! Form::model($participant, ['route' => ['participant.update', $participant->id], 'method' => 'PATCH']) !!}

        @include('participant._participant', ['submitLabel' => 'Update'])

    {!! Form::close() !!}

    @include('errors.validation-error')

    </div>
</div>

@stop

resources/views/participant/index.blade.php
@extends('layouts.app-base')

@section('content')

<div class="panel panel-primary">
    <div class="panel-heading">Participant</div>
    <div class="panel-body">

        <a href="{{ route('participant.create') }}" class="btn btn-success btn-sm mb-2">
            <i class="fa fa-plus-circle"></i> Create New
        </a>
        <table id="participantDtab" class="table table-xs table-striped table-bordered table-hover" width="100%">
            <thead>
                <tr>
                    <th width="125px"></th>
                    <th>Participant Number</th>
                    <th>Name</th>
                    <th>Identity Number</th>
                    <th>KTA Number</th>
                    <th>Institute</th>
                    <th>Email</th>
                    <th>Phone Number</th>
                    <th>Sex</th>
                </tr>
            </thead>
            <tbody>
                @forelse ($participants as $participant)
                    <tr>
                        <td class="align-middle">
                            <span>
                                <a href="{{ route('participant.edit', ['id' => $participant->id]) }}" class="btn btn-outline-primary btn-sm">
                                    <i class="fa fa-edit"></i>
                                </a>
                                <a onclick="return confirm('Are you sure?')" href="{{ route('participant.delete', ['id' => $participant->id]) }}" class="btn btn-outline-danger btn-sm">
                                    <i class="fa fa-trash"></i>
                                </a>
                            </span>
                        </td>
                        <td>{{ $participant->kode_peserta }}</td>
                        <td>{{ $participant->nama }}</td>
                        <td>{{ $participant->no_ktp }}</td>
                        <td>{{ $participant->no_kta }}</td>
                        <td>{{ $participant->institusi }}</td>
                        <td>{{ $participant->email }}</td>
                        <td>{{ $participant->no_telp }}</td>
                        <td>{{ $participant->jk }}</td>
                    </tr>
                @empty
                    <tr>
                        <td colspan="9" class="text-center text-muted">No data</td>
                        <td style="display: none;"></td>
                        <td style="display: none;"></td>
                        <td style="display: none;"></td>
                        <td style="display: none;"></td>
                        <td style="display: none;"></td>
                        <td style="display: none;"></td>
                        <td style="display: none;"></td>
                        <td style="display: none;"></td>
                    </tr>
                @endforelse
            </tbody>
        </table>

    </div>
</div>

<script>

$( document ).ready(function() {
    $('#participantDtab').DataTable({
        bLengthChange: false,
        columnDefs: [
            { orderable: false, targets: 0 }
        ],
        order: [[1, 'asc']],
        responsive: true
    });
});

</script>

@stop

@section('libs')

<script src="{{ asset('datatables/js/jquery.dataTables.min.js') }}"></script>
<script src="{{ asset('datatables-plugins/dataTables.bootstrap.min.js') }}"></script>
<script src="{{ asset('datatables-responsive/dataTables.responsive.js') }}"></script>

@stop