routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::group(['middleware' => ['auth']], function() {

    Route::get('/', 'DashboardController@index')->name('dashboard');

    Route::group(['middleware' => ['isAdmin']], function() {
        Route::resource('event', 'EventController', ['except' => ['destroy']]);
        Route::get('event/{event}/delete', 'EventController@destroy')->name('event.delete');

        Route::name('workshop.')->prefix('workshop')->group(function() {
            Route::get('create/{event}', 'WorkshopController@create')->name('create');
            Route::get('{workshop}/delete', 'WorkshopController@destroy')->name('delete');
            Route::get('schedule/{filterDate?}', 'WorkshopController@schedule')->name('schedule');
        });
        Route::resource('workshop', 'WorkshopController', ['except' => ['create', 'destroy']]);

        Route::name('session.')->prefix('session')->group(function() {
            Route::get('create/{workshop}', 'WorkshopSessionController@create')->name('create');
            Route::get('{workshop}/delete', 'WorkshopSessionController@destroy')->name('delete');
        });
        Route::resource('session', 'WorkshopSessionController', ['except' => ['create', 'destroy']]);

        Route::name('participant.')->prefix('participant')->group(function() {
            Route::get('{participant}/delete', 'ParticipantController@destroy')->name('delete');
            Route::get('create/{workshop}', 'ParticipantController@createInWorkshop')->name('createInWorkshop');
            Route::post('store/{workshop}', 'ParticipantController@storeInWorkshop')->name('storeInWorkshop');
            Route::get('show/{workshop}', 'ParticipantController@show')->name('showAvailable');
        });
        Route::resource('participant', 'ParticipantController', ['except' => ['destroy']]);
    });

    Route::group(['middleware' => ['isSuper']], function() {
        Route::prefix('user-management')->namespace('UserManagement')->group(function() {
            Route::resource('user', 'UserController', ['except' => ['destroy']]);
            Route::get('user/{user}/delete', 'UserController@destroy')->name('user.delete');
        });
    });
    
    Route::name('attendance.')->prefix('attendance')->group(function() {
        Route::get('/', 'ParticipantAttendanceController@index')->name('index');
        Route::get('{event}/workshop', 'ParticipantAttendanceController@workshop')->name('workshop');
        Route::get('{workshopSession}/scan', 'ParticipantAttendanceController@scan')->name('scan');
        Route::get('{workshopSession}/report', 'ParticipantAttendanceController@report')->name('report');
        Route::get('{event}/overallEventReport', 'EventController@overallReport')->name('overallEventReport');
        Route::get('{event}/exportOverallEventReport', 'EventController@exportOverallReport')->name('exportOverallEventReport');
        Route::get('{workshop}/overallReport', 'ParticipantAttendanceController@overallReport')->name('overallReport');
        Route::get('{workshop}/exportOverallReport', 'ParticipantAttendanceController@exportOverallReport')->name('exportOverallReport');
        Route::post('register', 'ParticipantAttendanceController@register')->name('register');
        Route::get('{attendance}/delete', 'ParticipantAttendanceController@destroy')->name('delete');
        Route::get('{event}/redirect', 'ParticipantAttendanceController@redirectToWorkshop')->name('redirect');
    });

    Route::prefix('api/v0')->namespace('Apis\v0')->group(function() {
        Route::get('/scan', 'ParticipantAttendanceController@scanBarcode')->name('scan');
        Route::get('/updateTime/{workshopId}/{participantId}', 'ParticipantAttendanceController@updateAttendanceParticipantTime')->name('updateTime');
    });

});

resources/views/session/_session.blade.php
<div class="form-group">
    {!! Form::hidden('id', null) !!}
    {!! Form::hidden('jadwal_materi_id', null) !!}
    {!! Form::label('sesi', 'Session:') !!}
    {!! Form::text('sesi', null, ['class' => 'form-control']) !!}
</div>
<div class="form-group">
    {!! Form::label('waktu_mulai', 'Session Time:') !!}
    {!! Form::text('waktu_mulai', null, ['class' => 'form-control']) !!}
</div>
<div class="form-group">
    {!! Form::submit($submitLabel, ['class' => 'btn btn-primary form-control']) !!}
    <a onclick="window.history.back()" type="button" class="btn btn-danger form-control text-white">Cancel</a>
</div>

<script>

$('#waktu_mulai').daterangepicker({
    timePicker: true,
    timePicker24Hour: true,
    timePickerSeconds: false,
    minDate: '{{ $minTime }}',
    maxDate: '{{ $maxTime }}',
    startDate: '{{ $startTime }}',
    endDate: '{{ $endTime }}',
    locale: {
        format: 'HH:mm'
    }
}).on('show.daterangepicker', function (ev, picker) {
    picker.container.find(".calendar-table").hide();
});

</script>

@section('libs')
    <script type="text/javascript" src="{{ asset('datetime-picker/moment.min.js') }}"></script>
    <script type="text/javascript" src="{{ asset('datetime-picker/daterangepicker.js') }}"></script>
    <link rel="stylesheet" href="{{ asset('datetime-picker/daterangepicker.css') }}" />
@stop

resources/views/session/_table.blade.php
<a href="{{ route('session.create', ['workshopId' => $workshop->id ]) }}" class="btn btn-success btn-sm mb-2">
    <i class="fa fa-plus-circle"></i> Create New Session
</a>
<table id="sessionDtab" class="table table-xs table-striped table-bordered" style="width=100%">
    <thead>
        <tr>
            <th width="50px"></th>
            <th>Session</th>
            <th>Start Time</th>
            <th>End Time</th>
            <th>Duration (minutes)</th>
        </tr>
    </thead>
    <tbody>
        @forelse ($sessions as $session)
            <tr>
                <td class="align-middle">
                    <span>
                        <a href="{{ route('session.edit', ['id' => $session->id]) }}" class="btn btn-outline-primary btn-sm">
                            <i class="fa fa-edit"></i>
                        </a>
                        <a onclick="return confirm('Are you sure?')" href="{{ route('session.delete', ['id' => $session->id]) }}" class="btn btn-outline-danger btn-sm">
                            <i class="fa fa-trash"></i>
                        </a>
                    </span>
                </td>
                <td>{{ $session->sesi }}</td>
                <td>{{ $session->waktu_mulai }}</td>
                <td>{{ $session->waktu_akhir }}</td>
                <td>{{ $session->durasi }}</td>
            </tr>
        @empty
            <tr>
                <td colspan="5" class="text-center text-muted">No data</td>
                <td style="display: none;"></td>
                <td style="display: none;"></td>
                <td style="display: none;"></td>
                <td style="display: none;"></td>
            </tr>
        @endforelse
    </tbody>
</table>

resources/views/session/create.blade.php
@extends('layouts.app-base')

@section('content')
<div class="panel panel-primary">
    <div class="panel-heading">Create Session</div>
    <div class="panel-body">

    {!! Form::model($workshopSession, ['route' => 'session.store']) !!}

        @include('session._session', ['submitLabel' => 'Save'])

    {!! Form::close() !!}

    @include('errors.validation-error')

    </div>
</div>

@stop

resources/views/session/edit.blade.php
@extends('layouts.app-base')

@section('content')

<div class="panel panel-primary">
    <div class="panel-heading">Edit Session</div>
    <div class="panel-body">

    {!! Form::model($session, ['route' => ['session.update', $session->id], 'method' => 'PATCH']) !!}

        @include('session._session', ['submitLabel' => 'Update'])

    {!! Form::close() !!}

    @include('errors.validation-error')

    </div>
</div>

@stop