routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::group(['middleware' => ['auth']], function() {

    Route::get('/', 'DashboardController@index')->name('dashboard');

    Route::group(['middleware' => ['isAdmin']], function() {
        Route::resource('event', 'EventController', ['except' => ['destroy']]);
        Route::get('event/{event}/delete', 'EventController@destroy')->name('event.delete');

        Route::name('workshop.')->prefix('workshop')->group(function() {
            Route::get('create/{event}', 'WorkshopController@create')->name('create');
            Route::get('{workshop}/delete', 'WorkshopController@destroy')->name('delete');
            Route::get('schedule/{filterDate?}', 'WorkshopController@schedule')->name('schedule');
        });
        Route::resource('workshop', 'WorkshopController', ['except' => ['create', 'destroy']]);

        Route::name('session.')->prefix('session')->group(function() {
            Route::get('create/{workshop}', 'WorkshopSessionController@create')->name('create');
            Route::get('{workshop}/delete', 'WorkshopSessionController@destroy')->name('delete');
        });
        Route::resource('session', 'WorkshopSessionController', ['except' => ['create', 'destroy']]);

        Route::name('participant.')->prefix('participant')->group(function() {
            Route::get('{participant}/delete', 'ParticipantController@destroy')->name('delete');
            Route::get('create/{workshop}', 'ParticipantController@createInWorkshop')->name('createInWorkshop');
            Route::post('store/{workshop}', 'ParticipantController@storeInWorkshop')->name('storeInWorkshop');
            Route::get('show/{workshop}', 'ParticipantController@show')->name('showAvailable');
        });
        Route::resource('participant', 'ParticipantController', ['except' => ['destroy']]);
    });

    Route::group(['middleware' => ['isSuper']], function() {
        Route::prefix('user-management')->namespace('UserManagement')->group(function() {
            Route::resource('user', 'UserController', ['except' => ['destroy']]);
            Route::get('user/{user}/delete', 'UserController@destroy')->name('user.delete');
        });
    });
    
    Route::name('attendance.')->prefix('attendance')->group(function() {
        Route::get('/', 'ParticipantAttendanceController@index')->name('index');
        Route::get('{event}/workshop', 'ParticipantAttendanceController@workshop')->name('workshop');
        Route::get('{workshopSession}/scan', 'ParticipantAttendanceController@scan')->name('scan');
        Route::get('{workshopSession}/report', 'ParticipantAttendanceController@report')->name('report');
        Route::get('{event}/overallEventReport', 'EventController@overallReport')->name('overallEventReport');
        Route::get('{event}/exportOverallEventReport', 'EventController@exportOverallReport')->name('exportOverallEventReport');
        Route::get('{workshop}/overallReport', 'ParticipantAttendanceController@overallReport')->name('overallReport');
        Route::get('{workshop}/exportOverallReport', 'ParticipantAttendanceController@exportOverallReport')->name('exportOverallReport');
        Route::post('register', 'ParticipantAttendanceController@register')->name('register');
        Route::get('{attendance}/delete', 'ParticipantAttendanceController@destroy')->name('delete');
        Route::get('{event}/redirect', 'ParticipantAttendanceController@redirectToWorkshop')->name('redirect');
    });

    Route::prefix('api/v0')->namespace('Apis\v0')->group(function() {
        Route::get('/scan', 'ParticipantAttendanceController@scanBarcode')->name('scan');
        Route::get('/updateTime/{workshopId}/{participantId}', 'ParticipantAttendanceController@updateAttendanceParticipantTime')->name('updateTime');
    });

});

resources/views/layouts/app-base.blade.php
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>PARI Courses Integrated System</title>

    <!-- Bootstrap Core CSS -->
    <link href="{{ asset('bootstrap/css/bootstrap.min.css') }}" rel="stylesheet">

    <!-- MetisMenu CSS -->
    <link href="{{ asset('metisMenu/metisMenu.min.css') }}" rel="stylesheet">

    <!-- DataTables CSS -->
    <link href="{{ asset('datatables-plugins/dataTables.bootstrap.css') }}" rel="stylesheet">

    <!-- DataTables Responsive CSS -->
    <link href="{{ asset('datatables-responsive/dataTables.responsive.css') }}" rel="stylesheet">

    <!-- Custom CSS -->
    <link href="{{ asset('dist/css/sb-admin-2.css') }}" rel="stylesheet">

    <!-- Custom Fonts -->
    <!-- <link href="{{ asset('css/all.min.css') }}" rel="stylesheet" type="text/css"> -->
    <link href="{{ asset('font-awesome/css/font-awesome.min.css') }}" rel="stylesheet" type="text/css">

    <link rel="stylesheet" href="{{ asset('css/pari-cis.css') }}">


    <!-- jQuery -->
    <script src="{{ asset('jquery/jquery.min.js') }}"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="{{ asset('bootstrap/js/bootstrap.min.js') }}"></script>

    <!-- Metis Menu Plugin JavaScript -->
    <script src="{{ asset('metisMenu/metisMenu.min.js') }}"></script>

    <!-- Custom Theme JavaScript -->
    <script src="{{ asset('dist/js/sb-admin-2.js') }}"></script>

    <!-- Datetime picker libs -->
    <script type="text/javascript" src="{{ asset('js/popper.min.js') }}"></script>

    <!-- Include libraries which not always needed in everypage -->
    @yield('libs')

    <!-- HTML5 Shim and Respond.js') }} IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js') }} doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js') }}"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js') }}/1.4.2/respond.min.js') }}"></script>
    <![endif]-->

</head>

<body>

    <div id="wrapper">

        <!-- Navigation -->
        @includeIf('layouts.navbar')

        <div id="page-wrapper">
            <!-- <div class="row">
                <div class="col-lg-12">
                    <h1 id="page-header" class="page-header"></h1>
                </div>
            </div> -->
            <!-- /.row -->
            <div class="row pt-4">
                <div class="col-lg-12">
                    @include('layouts.flash-notification')
                    @yield('content')
                </div>
                <!-- /.col-lg-12 -->
            </div>
            <!-- /.row -->
        </div>
        <!-- /#page-wrapper -->

    </div>
    <!-- /#wrapper -->

    <script>
        $('#flash-overlay-modal').modal();
        $('div.alert').not('.alert-important').delay(3000).slideUp(350);
    </script>

</body>

</html>

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ app()->getLocale() }}">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>PARI CIS</title>
    <link rel="icon" href="{{ asset('favicon.ico') }}">

    <!-- Styles -->
    <link href="{{ asset('bootstrap-3.3.7/css/bootstrap.css') }}" rel="stylesheet">

    <!-- JS -->
    <script type="text/javascript" src="{{ asset('jQuery-3.3.1/jquery-3.3.1.min.js') }}"></script>
    <script type="text/javascript" src="{{ asset('bootstrap-3.3.7/js/bootstrap.min.js') }}"></script>
</head>
<body>
    
    <div class="row">
        <div class="col-md-12">@include('layouts.top-navbar')</div>
    </div>
    <div class="row">
        <div class="col-md-12">
            <div class="container">
                @yield('content')
            </div>
        </div>
    </div>
</body>
</html>

resources/views/layouts/flash-notification.blade.php
@if (Session::has('flash_notification_message'))

    <div class="alert
                alert-{{ Session::has('flash_notification_level') ? session('flash_notification_level') : 'danger' }}
                {{ Session::has('flash_notification_important') ? 'alert-important' : '' }}"
                role="alert"
    >
        @if (Session::has('flash_notification_important'))
            <button type="button"
                    class="close"
                    data-dismiss="alert"
                    aria-hidden="true"
            >&times;</button>
        @endif

        {{ session('flash_notification_message') }}
    </div>

@endIf

resources/views/layouts/navbar.blade.php
<!-- Navigation -->
<nav class="navbar navbar-default navbar-static-top" role="navigation" style="margin-bottom: 0;background:#337ab7;">
    <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="{{ route('dashboard') }}" style="color:#fff">PARI Courses Integrated System</a>
    </div>
    <!-- /.navbar-header -->

    <ul class="nav navbar-top-links navbar-right">
        <!-- /.dropdown -->
        <li class="dropdown">
            <a class="dropdown-toggle" data-toggle="dropdown" href="#" style="color:#fff">
                {{ auth()->user()->name }}<i class="fa fa-user fa-fw"></i> <i class="fa fa-caret-down"></i>
            </a>
            <ul class="dropdown-menu dropdown-user">
                <li><a href="#" onclick="event.preventDefault();$('#logout-form').submit();"><i class="fa fa-sign-out fa-fw"></i> Logout</a></li>
            </ul>
            <form id="logout-form" action="{{ route('logout') }}" method="post" style="display:none;">{{ csrf_field() }}</form>
            <!-- /.dropdown-user -->
        </li>
        <!-- /.dropdown -->
    </ul>
    <!-- /.navbar-top-links -->

    <div class="navbar-default sidebar" role="navigation">
        <div class="sidebar-nav navbar-collapse">
            <ul class="nav" id="side-menu">
                <li>
                    <a href="{{ route('dashboard') }}"><i class="fa fa-dashboard fa-fw"></i> Dashboard</a>
                </li>
                <li>
                    <a href="{{ route('attendance.index') }}"><i class="fa fa-calendar-check-o fa-fw"></i> Workshop Attendance</a>
                </li>
                @if (auth()->user()->role_id == 1 || auth()->user()->role_id == 3)
                <li>
                    <a href="#"><i class="fa fa-calendar fa-fw"></i> Event Management<span class="fa arrow"></span></a>
                    <ul class="nav nav-second-level">
                        <li>
                            <a href="{{ route('event.index') }}">Events</a>
                        </li>
                        <li>
                            <a href="{{ route('participant.index') }}">Participants</a>
                        </li>
                    </ul>
                    <!-- /.nav-second-level -->
                </li>
                @if (auth()->user()->role_id == 3)
                <li>
                    <a href="{{ route('user.index') }}"><i class="fa fa-users fa-fw"></i> User Management</a>
                </li>
                @endIf
                @endIf
            </ul>
        </div>
        <!-- /.sidebar-collapse -->
    </div>
    <!-- /.navbar-static-side -->
</nav>

resources/views/layouts/top-navbar.blade.php
<nav class="navbar navbar-expand-sm bg-primary navbar-dark fixed-top shadow">
  <a class="navbar-brand" href="#">P-CiS</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="collapsibleNavbar">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <a class="nav-link" href="{{ route('welcome') }}">Home</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{{ route('attendance.index') }}">Workshop Attendance</a>
      </li>
      @if (Auth::user()->role_id == 1)
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbardrop" data-toggle="dropdown">
          Master
        </a>
        <div class="dropdown-menu">
          <a class="dropdown-item" href="{{ route('event.index') }}">Event</a>
          <a class="dropdown-item" href="{{ route('participant.index') }}">Participant</a>
        </div>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{{ route('user.index') }}">Admin</a>
      </li>
      @endIf
    </ul>
    <ul class="navbar-nav">
      <li class="nav-item">
        <a href="#" class="nav-link" onclick="event.preventDefault();$('#logout-form').submit();">Logout</a>
        <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
            {{ csrf_field() }}
        </form>
      </li>
    </ul>
  </div>
</nav>