routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::group(['middleware' => ['auth']], function() {

    Route::get('/', 'DashboardController@index')->name('dashboard');

    Route::group(['middleware' => ['isAdmin']], function() {
        Route::resource('event', 'EventController', ['except' => ['destroy']]);
        Route::get('event/{event}/delete', 'EventController@destroy')->name('event.delete');

        Route::name('workshop.')->prefix('workshop')->group(function() {
            Route::get('create/{event}', 'WorkshopController@create')->name('create');
            Route::get('{workshop}/delete', 'WorkshopController@destroy')->name('delete');
            Route::get('schedule/{filterDate?}', 'WorkshopController@schedule')->name('schedule');
        });
        Route::resource('workshop', 'WorkshopController', ['except' => ['create', 'destroy']]);

        Route::name('session.')->prefix('session')->group(function() {
            Route::get('create/{workshop}', 'WorkshopSessionController@create')->name('create');
            Route::get('{workshop}/delete', 'WorkshopSessionController@destroy')->name('delete');
        });
        Route::resource('session', 'WorkshopSessionController', ['except' => ['create', 'destroy']]);

        Route::name('participant.')->prefix('participant')->group(function() {
            Route::get('{participant}/delete', 'ParticipantController@destroy')->name('delete');
            Route::get('create/{workshop}', 'ParticipantController@createInWorkshop')->name('createInWorkshop');
            Route::post('store/{workshop}', 'ParticipantController@storeInWorkshop')->name('storeInWorkshop');
            Route::get('show/{workshop}', 'ParticipantController@show')->name('showAvailable');
        });
        Route::resource('participant', 'ParticipantController', ['except' => ['destroy']]);
    });

    Route::group(['middleware' => ['isSuper']], function() {
        Route::prefix('user-management')->namespace('UserManagement')->group(function() {
            Route::resource('user', 'UserController', ['except' => ['destroy']]);
            Route::get('user/{user}/delete', 'UserController@destroy')->name('user.delete');
        });
    });
    
    Route::name('attendance.')->prefix('attendance')->group(function() {
        Route::get('/', 'ParticipantAttendanceController@index')->name('index');
        Route::get('{event}/workshop', 'ParticipantAttendanceController@workshop')->name('workshop');
        Route::get('{workshopSession}/scan', 'ParticipantAttendanceController@scan')->name('scan');
        Route::get('{workshopSession}/report', 'ParticipantAttendanceController@report')->name('report');
        Route::get('{event}/overallEventReport', 'EventController@overallReport')->name('overallEventReport');
        Route::get('{event}/exportOverallEventReport', 'EventController@exportOverallReport')->name('exportOverallEventReport');
        Route::get('{workshop}/overallReport', 'ParticipantAttendanceController@overallReport')->name('overallReport');
        Route::get('{workshop}/exportOverallReport', 'ParticipantAttendanceController@exportOverallReport')->name('exportOverallReport');
        Route::post('register', 'ParticipantAttendanceController@register')->name('register');
        Route::get('{attendance}/delete', 'ParticipantAttendanceController@destroy')->name('delete');
        Route::get('{event}/redirect', 'ParticipantAttendanceController@redirectToWorkshop')->name('redirect');
    });

    Route::prefix('api/v0')->namespace('Apis\v0')->group(function() {
        Route::get('/scan', 'ParticipantAttendanceController@scanBarcode')->name('scan');
        Route::get('/updateTime/{workshopId}/{participantId}', 'ParticipantAttendanceController@updateAttendanceParticipantTime')->name('updateTime');
    });

});

resources/views/attendance/index.blade.php
@extends('layouts.app-base')

@section('content')

<div class="row mb-2">
@forelse ($events as $event)
  <div class="col-sm-6">
    <div class="panel panel-primary">
      <div class="panel-body text-white bg-primary" style="height:150px; overflow-y:auto">
        <h3>{{$event->nama}}</h3>
        <p class="card-text">{{$event->keterangan}}</p>
      </div>
      <ul class="list-group">
        <li class="list-group-item" style="height:50px">
          <div class="row">
            <div class="col-md-1"><strong>Place</strong></div>
            <div class="col-md-1"><strong>:</strong></div>
            <div class="col-md-10">{{$event->tempat}}</div>
          </div>
        </li>
        <li class="list-group-item" style="height:50px">
          <div class="row">
            <div class="col-md-1"><strong>Date</strong></div>
            <div class="col-md-1"><strong>:</strong></div>
            <div class="col-md-10">{{$event->tanggal_mulai}} to {{$event->tanggal_akhir}}</div>
          </div>
        </li>
      </ul>
      <div class="panel-footer text-right">
        <a href="{{ route('attendance.overallEventReport', ['eventId' => $event->id]) }}" class="btn btn-info btn-show">
            <i class="fa fa-book"></i> Event Report
        </a>
        <a href="{{ route('attendance.workshop', ['eventId' => $event->id]) }}" class="btn btn-success btn-show">
            <i class="fa fa-desktop"></i> View Workshop
        </a>
      </div>
    </div>
  </div>
@empty
  <div class="alert alert-secondary" role="alert">
    No event data yet, @if(auth()->user()->role_id != 1) please contact your administrator @else please input event data first in <a href="{{ route('event.index') }}">here <i class="fa fa-external-link"></i></a> @endIf
  </div>
@endForelse
</div>

<script>

$( document ).ready(function() {
  // $('.btn-show').click(function(e) {
  //   e.preventDefault();
  //   url = this.href;
  //   dt = new Date();
  //   year = dt.getFullYear();
  //   month = dt.getMonth() + 1;
  //   day = dt.getDate();
  //   hour = dt.getHours();
  //   minute = dt.getMinutes();
  //   clientsLocalTime = year +'-'+ month +'-'+ day +' '+ hour +':'+ minute +':00';
  //   url = url + '?clients_local_time=' + clientsLocalTime;
  //   window.location = url; 
  // });
    // $('div.eventButtonTable').html('<button type="button" class="btn btn-sm btn-success pull-left m-0">Tambah</button>');

    // $('#eventDtab').DataTable({
    //     // dom : '<""<"eventButtonTable">f>tp',
    // });
});

</script>

@stop

@section('libs')

<!-- <link rel="stylesheet" type="text/css" href="{{ asset('datatables/datatables.css') }}">
<script type="text/javascript" charset="utf8" src="{{ asset('datatables/datatables.js') }}"></script> -->

@stop

resources/views/attendance/overall-event-report.blade.php
@extends('layouts.app-base')

@section('content')

<button onclick="window.open('{{ route('attendance.exportOverallEventReport', ['eventId' => $event->id]) }}')" class="btn btn-info btn-sm text-white text-sm-center mb-2">
    <i class="fa fa-file-excel-o"></i> Export
</button>
<a href="{{ route('attendance.index') }}" class="btn btn-danger btn-sm text-white text-sm-center mb-2">
    <i class="fa fa-arrow-circle-o-left"></i> Back
</a>

<table class="table table-sm">
    <tr>
        <td>Event</td>
        <td>{{ $event->nama }}</td>
    </tr>
    <tr>
        <td>Place</td>
        <td>{{ $event->tempat }}</td>
    </tr>
    <tr>
        <td>Time</td>
        <td>{{ $event->tanggal_mulai }} to {{ $event->tanggal_akhir }}</td>
    </tr>
    <tr>
        <td>Total Duration</td>
        <td>{{ $event->durasi }} minutes</td>
    </tr>
</table>

<div class="panel panel-primary">
    <div class="panel-heading">Attendance Event Report</div>
    <div class="panel-body">

        <table id="participantDtab" class="table table-xs table-striped table-bordered table-hover" width="100%">
            <thead>
                <tr>
                    <th>Participant Number</th>
                    <th>Name</th>
                    <th>Identity Number</th>
                    <th>KTA Number</th>
                    <th>Institute</th>
                    <th>Total Time Attendance (Minutes)</th>
                    <th>Attendance Percentage</th>
                    <th>Pass Status</th>
                </tr>
            </thead>
            <tbody>
                @forelse ($participants as $participant)
                    <tr>
                        <td>{{ $participant->kode_peserta }}</td>
                        <td>{{ $participant->nama }}</td>
                        <td>{{ $participant->no_ktp }}</td>
                        <td>{{ $participant->no_kta }}</td>
                        <td>{{ $participant->institusi }}</td>
                        <td>{{ $participant->waktu_kehadiran }}</td>
                        <td>{{ $participant->persentase_kehadiran }} %</td>
                        <td>@if($participant->persentase_kehadiran >= 75) Passed @else Not Passed @endIf</td>
                    </tr>
                @empty
                    <tr>
                        <td colspan="8" class="text-center text-muted">No data</td>
                    </tr>
                @endforelse
            </tbody>
        </table>

    </div>
</div>


<script>

$( document ).ready(function() {
    $('#participantDtab').DataTable({
        order: [[0, 'asc'], [1, 'asc']],
        responsive: true
    });
});

</script>

@stop

@section('libs')

<script src="{{ asset('datatables/js/jquery.dataTables.min.js') }}"></script>
<script src="{{ asset('datatables-plugins/dataTables.bootstrap.min.js') }}"></script>
<script src="{{ asset('datatables-responsive/dataTables.responsive.js') }}"></script>

@stop

resources/views/attendance/overall-report.blade.php
@extends('layouts.app-base')

@section('content')


<button onclick="window.open('{{ route('attendance.exportOverallReport', ['workshopId' => $workshop->id]) }}')" class="btn btn-info btn-sm text-white text-sm-center mb-2">
    <i class="fa fa-file-excel-o"></i> Export
</button>
<a href="{{ route('attendance.workshop', ['eventId' => $workshop->event_id]) }}" class="btn btn-danger btn-sm text-white text-sm-center mb-2">
    <i class="fa fa-arrow-circle-o-left"></i> Back
</a>

<table class="table table-sm">
    <tr>
        <td>Workshop</td>
        <td>{{ $workshop->judul_materi }}</td>
    </tr>
    <tr>
        <td>Speaker</td>
        <td>{{ $workshop->pengisi_materi }}</td>
    </tr>
    <tr>
        <td>Place</td>
        <td>{{ $workshop->tempat }}</td>
    </tr>
    <tr>
        <td>Time</td>
        <td>{{ $workshop->waktu_mulai }} to {{ $workshop->waktu_akhir }}</td>
    </tr>
</table>

<div class="panel panel-primary">
    <div class="panel-heading">Attendance Workshop Report</div>
    <div class="panel-body">

        <table id="participantDtab" class="table table-xs table-striped table-bordered table-hover" width="100%">
            <thead>
                <tr>
                    <th>Participant Number</th>
                    <th>Name</th>
                    <th>Identity Number</th>
                    <th>KTA Number</th>
                    <th>Institute</th>
                    <th>Total Time Attendance (Minutes)</th>
                    <th>Attendance Percentage</th>
                    <th>Pass Status</th>
                </tr>
            </thead>
            <tbody>
                @forelse ($participants as $participant)
                    <tr>
                        <td>{{ $participant->kode_peserta }}</td>
                        <td>{{ $participant->nama }}</td>
                        <td>{{ $participant->no_ktp }}</td>
                        <td>{{ $participant->no_kta }}</td>
                        <td>{{ $participant->institusi }}</td>
                        <td>{{ $participant->waktu_kehadiran }}</td>
                        <td>{{ $participant->persentase_kehadiran }} %</td>
                        <td>@if($participant->persentase_kehadiran >= 75) Passed @else Not Passed @endIf</td>
                    </tr>
                @empty
                    <tr>
                        <td colspan="8" class="text-center text-muted">No data</td>
                    </tr>
                @endforelse
            </tbody>
        </table>

    </div>
</div>


<script>

$( document ).ready(function() {
    $('#participantDtab').DataTable({
        order: [[0, 'asc'], [1, 'asc']],
        responsive: true
    });
});

</script>

@stop

@section('libs')

<script src="{{ asset('datatables/js/jquery.dataTables.min.js') }}"></script>
<script src="{{ asset('datatables-plugins/dataTables.bootstrap.min.js') }}"></script>
<script src="{{ asset('datatables-responsive/dataTables.responsive.js') }}"></script>

@stop

resources/views/attendance/report.blade.php
@extends('layouts.app-base')

@section('content')

<a href="{{ route('attendance.scan', ['sessionId' => $session->id]) }}" class="btn btn-danger btn-sm text-white text-sm-center mb-2">
    <i class="fa fa-arrow-circle-o-left"></i> Back
</a>

<table class="table table-sm">
    <tr>
        <td>Workshop</td>
        <td>{{ $workshop->judul_materi }}</td>
    </tr>
    <tr>
        <td>Speaker</td>
        <td>{{ $workshop->pengisi_materi }}</td>
    </tr>
    <tr>
        <td>Place</td>
        <td>{{ $workshop->tempat }}</td>
    </tr>
    <tr>
        <td>Time</td>
        <td>{{ $workshop->waktu_mulai }} to {{ $workshop->waktu_akhir }}</td>
    </tr>
    <tr>
        <td>Sesion</td>
        <td>{{ $session->sesi }}</td>
    </tr>
</table>


<div class="panel panel-primary">
    <div class="panel-heading">Attendance Session Report</div>
    <div class="panel-body">

        <table id="participantDtab" class="table table-xs table-striped table-bordered table-hover" width="100%">
            <thead>
                <tr>
                    <th>Participant Number</th>
                    <th>Name</th>
                    <th>Identity Number</th>
                    <th>KTA Number</th>
                    <th>Institute</th>
                    <th>Check In</th>
                    <th>Check Out</th>
                    <th>Time Attendance (Minutes)</th>
                </tr>
            </thead>
            <tbody>
                @forelse ($participants as $participant)
                    <tr>
                        <td>{{ $participant->kode_peserta }}</td>
                        <td>{{ $participant->nama }}</td>
                        <td>{{ $participant->no_ktp }}</td>
                        <td>{{ $participant->no_kta }}</td>
                        <td>{{ $participant->institusi }}</td>
                        <td>{{ $participant->check_in }}</td>
                        <td>{{ $participant->check_out }}</td>
                        <td>{{ $participant->waktu_kehadiran }}</td>
                    </tr>
                @empty
                    <tr>
                        <td colspan="8" class="text-center text-muted">No data</td>
                        <td style="display: none;"></td>
                        <td style="display: none;"></td>
                        <td style="display: none;"></td>
                        <td style="display: none;"></td>
                        <td style="display: none;"></td>
                        <td style="display: none;"></td>
                        <td style="display: none;"></td>
                    </tr>
                @endforelse
            </tbody>
        </table>

    </div>
</div>

<script>

$( document ).ready(function() {
    $('#participantDtab').DataTable({
        order: [[0, 'asc'], [1, 'asc']],
        responsive: true
    });
});

</script>

@stop

@section('libs')

<script src="{{ asset('datatables/js/jquery.dataTables.min.js') }}"></script>
<script src="{{ asset('datatables-plugins/dataTables.bootstrap.min.js') }}"></script>
<script src="{{ asset('datatables-responsive/dataTables.responsive.js') }}"></script>

@stop

resources/views/attendance/scan.blade.php
@extends('layouts.app-base')

@section('content')

<div class="panel panel-primary mb-4">
    <div class="panel-heading">{{ $workshop->judul_materi }} - {{ $session->sesi }}</div>
    <div class="panel-body">
        <div class="row">
            <div class="col-sm-2">Speaker</div>
            <div class="col-sm-10 text-muted">{{ $workshop->pengisi_materi }}</div>
        </div>
        <div class="row">
            <div class="col-sm-2">Place/Room</div>
            <div class="col-sm-10 text-muted">{{ $workshop->tempat }}</div>
        </div>
        <div class="row">
            <div class="col-sm-2">Description</div>
            <div class="col-sm-10 text-muted">{{ $workshop->deskripsi }}</div>
        </div>
        <div class="row">
            <div class="col-sm-2">Session</div>
            <div class="col-sm-10 text-muted">{{ $session->sesi }}</div>
        </div>
        <div class="row">
            <div class="col-sm-2">Session Time</div>
            <div class="col-sm-10 text-muted">{{ $session->waktu_mulai->format('H:i') }} to {{ $session->waktu_akhir->format('H:i') }}</div>
        </div>
        <div class="row">
            <div class="col-sm-2">Duration</div>
            <div class="col-sm-10 text-muted">{{ $session->durasi }} Minutes</div>
        </div>
        <div class="text-right">
            <a href="{{ route('attendance.report', ['sessionId' => $session->id]) }}" class="btn btn-info btn-sm text-white text-sm-center mt-2">
                <i class="fa fa-book"></i> Attendance Report
            </a>
            <a href="{{ route('attendance.workshop', ['eventId' => $workshop->event_id]) }}" class="btn btn-danger btn-sm text-white text-sm-center mt-2">
                <i class="fa fa-arrow-circle-o-left"></i> Back
            </a>
        </div>
    </div>
</div>

{!! Form::open(['id' => 'scan-form']) !!}

<div class="input-group">
    <input type="text" class="form-control" id="barcode" placeholder="Scan or Input The Participant Number..." autofocus>
    <div class="input-group-btn">
        <button class="btn btn-primary" type="submit"><span class="fa fa-barcode"></span> Scan</button>
    </div>
</div>

{!! Form::close() !!}

<div id="alert-scan" class="alert alert-success mt-4" role="alert" style="display:none">
    <label id="alert-label">molohok</label>
</div>

<script>

$(document).ready(function() {

start = moment('{{ $session->waktu_mulai }}').subtract({ hours:1 });
end = '{{ $session->waktu_akhir }}';
if (!moment().isBetween(start, end)) {
    urlRedirect = "{{ route('attendance.redirect', ['eventId' => $workshop->event_id]) }}?sesi={{ $session->sesi }}&judul_materi={{ $workshop->judul_materi }}";
    // window.location = urlRedirect;
}

$('#barcode').focusout(function(){
    $('#barcode').focus();
});

$('#scan-form').submit(function(e) {
    e.preventDefault();
    barcode = $('#barcode').val();
    scanTime = moment().format('YYYY-MM-DD HH:mm');

    $.ajax({
        type: 'GET',
        url: "{{ route('scan') }}",
        data: {
            workshop_id: {{ $workshop->id }},
            session_id: {{ $session->id }},
            barcode: barcode,
            scan_time: scanTime
        },
        beforeSend: function() {
            $('#alert-scan').hide();
        },
        success: function(result) {
            $('#alert-scan').removeClass('alert-danger');
            $('#alert-scan').removeClass('alert-success');
            if (result.success != false) {
                $('#alert-scan').addClass('alert-success');
            } else {
                $('#alert-scan').addClass('alert-danger');
            }
            $('#alert-label').text(result.message);
            $('#alert-scan').slideDown(300);
            $('#alert-scan').delay(3000).slideUp(300);
        },
        complete: function() {
            $('#barcode').val('').focus();
        },
        error: function(result, status, xhr) {
            if (result.status == 404) {
                message = result.responseJSON.message;
                urlRedirect = "{{ route('attendance.redirect', ['eventId' => $workshop->event_id]) }}?sesi={{ $session->sesi }}&judul_materi={{ $workshop->judul_materi }}";
                window.location = urlRedirect;
            } else {
                $('#alert-scan').removeClass('alert-danger');
                $('#alert-scan').removeClass('alert-success');
                $('#alert-scan').addClass('alert-danger');
                $('#alert-label').text(result.responseJSON.message);
                $('#alert-scan').slideDown(300);
                $('#alert-scan').delay(3000).slideUp(300);
            }
        }
    });
});

});

</script>

@stop

@section('libs')
  <script type="text/javascript" src="{{ asset('datetime-picker/moment.min.js') }}"></script>
@stop

resources/views/attendance/workshop.blade.php
@extends('layouts.app-base')

@section('content')

<div class="row mb-2">
@forelse ($workshops as $workshop)
  <div class="col-sm-4">
    <div class="panel panel-primary">
      <div class="panel-body text-white bg-primary" style="height:125px; overflow-y:auto">
        <h3>{{$workshop->judul_materi}}</h3>
        <p class="card-text">{{$workshop->deskripsi}}</p>
      </div>
      <ul class="list-group">
        <li class="list-group-item">
          <div class="row">
            <div class="col-md-12"><strong>Speaker</strong></div>
          </div>
          <div class="row">
            <div class="col-md-12">{{$workshop->pengisi_materi}}</div>
          </div>
        </li>
        <li class="list-group-item">
          <div class="row">
            <div class="col-md-12"><strong>Place/Room</strong></div>
          </div>
          <div class="row">
            <div class="col-md-12">{{$workshop->tempat}}</div>
          </div>
        </li>
        <li class="list-group-item">
          <div class="row">
            <div class="col-md-12"><strong>Time</strong></div>
          </div>
          <div class="row">
            <div class="col-md-12">{{$workshop->waktu_mulai}} to {{$workshop->waktu_akhir}}</div>
          </div>
        </li>
        <li class="list-group-item">
          <div class="row">
            <div class="col-md-12"><strong>Session</strong></div>
          </div>
          <div class="row">
            <div class="col-md-12">
                <select id="session-{{ $workshop->id }}-dropdown" class="form-control">
                  @foreach (($workshop->sessions()->get()) as $session)
                    <option value="{{ $session->id }}" disabled data-start="{{ $session->waktu_mulai->format('Y-m-d H:i') }}" data-end="{{ $session->waktu_akhir->format('Y-m-d H:i') }}">
                      {{ $session->sesi }} [ {{ $session->waktu_mulai->format('H:i') }} - {{ $session->waktu_akhir->format('H:i') }} ]
                    </option>
                  @endforeach
                </select>
            </div>
          </div>
        </li>
      </ul>
      <div class="panel-footer text-right">
        <a href="{{ route('attendance.overallReport', ['workshopId' => $workshop->id]) }}" class="btn btn-sm btn-info">
            <i class="fa fa-book"></i> Attendance Report
        </a>
        <a class="btn btn-sm btn-success" onclick="redirectToScan({{ $workshop->id }})">
            <i class="fa fa-calendar-check-o"></i> Attendance
        </a>
      </div>
    </div>
  </div>
@empty
  <div class="alert alert-secondary" role="alert">
    No workshop data yet in <strong>{{ $event->nama }}</strong> event, @if(auth()->user()->role_id != 1) please contact your administrator @else please input workshop data first in <a href="{{ route('event.show', ['id' => $event->id]) }}">here <i class="fa fa-external-link"></i></a> @endIf
  </div>
@endForelse
</div>
<script>

$( document ).ready(function() {
    $('select[id^=session-] > option').each(function() {
      start = moment($(this).data('start')).subtract({ hours:1 });
      end = $(this).data('end');

      if (moment().isBetween(start, end)) {
        $(this).removeAttr('disabled');
        $(this).attr('selected', 'selected');
      }
    });
});

function redirectToScan(workshopId) {
    sessionId = $('#session-'+ workshopId +'-dropdown').val();

    if (sessionId) {
      url = "{{ route('attendance.scan', ['sessionId' => 'sessionId']) }}";
      url = url.replace('sessionId', sessionId);
      window.location.href = url;
    } else {
      alert('Please choose the workshop\'s session first');
    }
}

</script>

@stop

@section('libs')
  <script type="text/javascript" src="{{ asset('datetime-picker/moment.min.js') }}"></script>
@stop